export const jwtConstants = {
  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
  ACCESS_TOKEN_EXP: process.env.ACCESS_TOKEN_EXP,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  REFRESH_TOKEN_EXP: process.env.REFRESH_TOKEN_EXP,
};
